<?php

$repos = array(
    'hanwan' => "https://hawa130.com/feed",
    'mukiispace' => 'https://www.mukiispace.tk/rss/feed.xml',
    "reverier" => 'https://blog.woooo.tech/index.xml',
    'ray' => 'http://ray.al/?feed=atom',
    'xiaobei' => 'http://blog.xiaobeo.top/index.php/feed/',
    'benderblog' => 'https://www.superbart.xyz/index.xml',
    'shifeiti' => 'https://www.shifeiti.com/atom.xml',
    'xeonds' => 'https://xeonds.github.io/atom.xml',
    'orangecheers' => 'https://honoka.tech/atom.xml',
    'ksfu' => 'https://blog.ksfu.top/atom.xml',
    'deanoffice' => 'https://rsshub.app/xidian/jwc/tzgg',
    'xinhua' => 'https://rsshub.app/news/whxw',
    'southern' => 'https://rsshub.app/infzm/2',
    'solidot' => 'https://www.solidot.org/index.rss',
    'linuxcn' => 'https://linux.cn/rss.xml',
    'lianhe' => 'https://rsshub.app/zaobao/realtime/china',
    'tvb' => 'https://rsshub.app/tvb/news/focus/sc',
    'tdm' => "https://cdn.tdm.com.mo/xml/rss/zh_news.xml",
    'kbs' => 'https://rsshub.app/kbs/news/all/c',
    'kcna' => 'https://rsshub.app/kcna/cn',
    'aljazeera' => 'https://rsshub.app/aljazeera/chinese/news',
    'sputnik' => 'https://rsshub.app/sputniknews/news/chinese',
    'coolapk' => 'https://rsshub.app/coolapk/toutiao',
    'thbwiki' => 'https://rsshub.app/thwiki/calendar',
    'ft' => 'https://rsshub.app/ft/chinese/hotstoryby7day',
);
